services:
  hackapay-user:
    image: 'hackapay-user-image'
    build:
      context: .
    container_name: 'hackapay-user-container'
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/hackapay-user-db
      - SPRING_DATASOURCE_USERNAME=hackaPay
      - SPRING_DATASOURCE_PASSWORD=hackaPayUser
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    networks:
      - hackapay-network
  db:
    image: postgres:latest
    container_name: hackapay-user-db
    command: -p 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hackaPay
      - POSTGRES_PASSWORD=hackaPayUser
      - POSTGRES_DB=hackapay-user-db
    networks:
      - hackapay-network
networks:
  hackapay-network:
    external: true